
/**
 * Expose `Actions`
 */

exports = module.exports = Actions;


/**
 * `Actions` are generated by `Views` and processed by the `Dispacher` according to the
 * Flux application architecture.
 *
 * @param {Dispacher} dispacher
 */
function Actions(dispacher) {
  this.dispacher = dispacher;
}

/**
 * Sample action.
 */
Actions.prototype.increment = function() {
  this.dispacher.dispatch({
      source: 'view',
      action: {
        actionType: 'increment'
      }
    });
};

/**
 * Sample action.
 */
Actions.prototype.decrement = function() {
  this.dispacher.dispatch({
      source: 'view',
      action: {
        actionType: 'decrement'
      }
    });
};
